COMMENT_MAP = {
    "alsa-utils": [
        ['/amixer/.*', 'amixer'],
        ['/alsamixer/.*', 'alsamixer'],
        ['/aplay/.*', 'aplay/arecord'],
        ['/alsaconf/.*', 'alsaconf'],
        ['/speaker-test/.*', 'Speaker Test'],
        ['/alsactl/.*', 'ALSA Control (alsactl)'],
        ['/amidi/.*', 'ALSA RawMidi Utility (amidi)'],
        ['/seq/aplaymidi/.*', 'aplaymidi/arecordmidi'],
        ['/seq/aseqdump/.*', 'aseqdump'],
        ['/seq/aconnect/.*', 'aconnect'],
        ['/seq/aseqnet/.*', 'aseqnet'],
        ['/iecset/.*', 'iecset'],
        ['/configure.in', 'Core'],
        ['/Makefile.am', 'Core'],
        ['/Makefile.am', 'Core'],
        ['/README', 'Core'],
        ['/INSTALL', 'Core'],
        ['/include/gettext.h', 'IGNORE'],
        ['/po/.*', 'IGNORE'],
        ['/m4/.*', 'IGNORE'],
        ['/utils/alsa-utils.spec.in', 'Core'],
        ['/cvscompile', 'cvscompile'],
        ['/hgcompile', 'hgcompile'],
        ['/gitcompile', 'gitcompile'],
        ['/ChangeLog', 'IGNORE'],
        ['/', 'ERROR'],
    ],
    "alsa-driver": [
        ['/include/cs8403.h', 'CS8403'],
        ['/include/mpu401.h', 'MPU401 UART'],
        ['/drivers/mpu401', 'MPU401 UART'],
        ['/include/asound_fm.h', 'Raw OPL FM'],
        ['/include/opl3.h', 'OPL3'],
        ['/drivers/opl3', 'OPL3'],
        ['/drivers/opl4', 'OPL4'],
        ['/include/opl4.h', 'OPL4'],
        ['/include/vx_core.h', 'Digigram VX core'],
        ['/drivers/vx', 'Digigram VX core'],
        ['/drivers', 'Generic drivers'],
        ['/include/uda1341.h', 'UDA1341'],
        ['/arm/Kconfig', 'ARM'],
        ['/arm/devdma.[ch]', 'ARM DMA routines'],
        ['/arm/aaci.[ch]', 'ARM AACI PL041 driver'],
        ['/arm/sa11xx-uda1341.(c|patch)', 'SA11xx UDA1341 driver'],
        ['/include/pxa2xx-lib.h', 'ARM PXA2XX driver'],
        ['/arm/pxa2xx.*', 'ARM PXA2XX driver'],
        ['/arm/s3c24xx-iis.[ch]', 'ARM S3C24XX IIS driver'],
        ['/arm', 'ERROR'],
        ['/isa/Kconfig', 'ISA'],
        ['/include/wss.h', 'WSS library'],
        ['/isa/wss/.*', 'WSS library'],
        ['/include/ad1816a.h', 'AD1816A driver'],
        ['/isa/ad1816a', 'AD1816A driver'],
        ['/include/ad1843.h', 'AD1843 driver'],
        ['/include/ad1848.h', 'AD1848 driver'],
        ['/isa/ad1848', 'AD1848 driver'],
        ['/isa/sc6000.c', 'SC6000 (CompuMedia ASC-9308 + AD1848) driver'],
        ['/include/cs4231(|-regs).h', 'CS4231 driver'],
        ['/isa/cs423x/cs4231.*', 'CS4231 driver'],
        ['/isa/cs423x/cs4236.*', 'CS4236+ driver'],
        ['/isa/cs423x/.*pc98.*', 'PC98(CS423x) driver'],
        ['/isa/cs423x', 'CS423x drivers'],
        ['/include/es1688.h', 'ES1688 driver'],
        ['/isa/es1688', 'ES1688 driver'],
        ['/include/gus.h', 'GUS Library'],
        ['/isa/gus/gus_.*', 'GUS Library'],
        ['/isa/gus/gusclassic.c', 'GUS Classic driver'],
        ['/isa/gus/gusextreme.c', 'GUS Extreme driver'],
        ['/isa/gus/gusmax.c', 'GUS MAX driver'],
        ['/isa/gus/interwave.*', 'AMD InterWave driver'],
        ['/isa/gus', 'GUS drivers'],
        ['/include/sb.h', 'SB drivers'],
        ['/isa/sb/es968.c', 'ES968 driver'],
        ['/include/sfnt_info.h', 'SoundFont'],
        ['/include/soundfont.h', 'SoundFont'],
        ['/include/emu8000.h', 'EMU8000 driver'],
        ['/isa/sb/emu8000.*', 'EMU8000 driver'],
        ['/isa/sb/sb16.*', 'SB16/AWE driver'],
        ['/include/sb16_csp.h', 'SB16/AWE driver'],
        ['/isa/sb/sb8.*', 'SB8 driver'],
        ['/isa/sb', 'SB drivers'],
        ['/isa/msnd', 'MSND driver'],
        ['/isa/opti9xx', 'Opti9xx drivers'],
        ['/include/yss225.h', 'Wavefront drivers'],
        ['/include/wavefront.*.h', 'Wavefront drivers'],
        ['/include/snd_wavefront.h', 'Wavefront drivers'],
        ['/isa/wavefront', 'Wavefront drivers'],
        ['/isa/als100.c', 'ALS100 driver'],
        ['/isa/azt2320.c', 'AZT2320 driver'],
        ['/isa/cmi8330.c', 'CMI8330 driver'],
        ['/isa/dt019x.c', 'DT019x driver'],
        ['/isa/es18xx.c', 'ES18xx driver'],
        ['/isa/opl3sa2.c', 'OPL3SA2 driver'],
        ['/isa/sgalaxy.c', 'Sound Galaxy driver'],
        ['/include/sscape_ioctl.h', 'Sound Scape driver'],
        ['/isa/sscape.c', 'Sound Scape driver'],
        ['/isa/adlib.c', 'Adlib FM driver'],
        ['/isa', 'ERROR'],
        ['/include/ak4531_codec.h', 'AK4531 codec'],
        ['/pci/ac97/ak4531_codec.c', 'AK4531 codec'],
        ['/pci/ak4531_codec.c', 'AK4531 codec'],
        ['/include/ac97_codec.h', 'AC97 Codec'],
        ['/pci/ac97', 'AC97 Codec'],
        ['/pci/ali5451', 'ALI5451 driver'],
        ['/include/emu10k1.*.h', 'EMU10K1/EMU10K2 driver'],
        ['/pci/emu10k1', 'EMU10K1/EMU10K2 driver'],
        ['/pci/au88x0', 'au88x0 driver'],
        ['/pci/ice1712/envy24ht.h', 'ICE1724 driver'],
        ['/pci/ice1712/revo.(c|h)', 'ICE1724 driver'],
        ['/pci/ice1712/amp.(c|h)', 'ICE1724 driver'],
        ['/pci/ice1712/ice1724.c', 'ICE1724 driver'],
        ['/pci/ice1712', 'ICE1712 driver'],
        ['/pci/korg1212', 'KORG1212 driver'],
        ['/pci/mixart', 'MIXART driver'],
        ['/pci/nm256', 'NM256 driver'],
        ['/include/hdsp.h', 'RME HDSP driver'],
        ['/pci/rme9652/hdsp.c', 'RME HDSP driver'],
        ['/pci/rme9652', 'RME9652 driver'],
        ['/include/ymfpci.h', 'YMFPCI driver'],
        ['/pci/ymfpci', 'YMFPCI driver'],
        ['/include/trident.h', 'Trident driver'],
        ['/pci/trident', 'Trident driver'],
        ['/pci/vx222', 'Digigram VX222 driver'],
        ['/include/cs46xx.*.h', 'CS46xx driver'],
        ['/pci/cs46xx', 'CS46xx driver'],
        ['/pci/asihpi', 'Asihpi driver'],
        ['/pci/echoaudio', 'Echoaudio driver'],
        ['/pci/pdplus', 'PDPlus driver'],
        ['/pci/als4000.c', 'ALS4000 driver'],
        ['/pci/azt3328.[ch]', 'AZT3328 driver'],
        ['/pci/cmipci.(c|patch)', 'CMIPCI driver'],
        ['/pci/cs4281.c', 'CS4281 driver'],
        ['/pci/ens1370.(c|patch)', 'ENS1370/1+ driver'],
        ['/pci/ens1371.c', 'ENS371+ driver'],
        ['/pci/es1938.c', 'ES1938 driver'],
        ['/pci/es1968.c', 'ES1968 driver'],
        ['/pci/fm801.(c|patch)', 'FM801 driver'],
        ['/pci/intel8x0.(c|patch)', 'Intel8x0 driver'],
        ['/pci/maestro3.(c|patch)', 'Maestro3 driver'],
        ['/pci/rme32.c', 'RME32 driver'],
        ['/pci/rme96.c', 'RME96 driver'],
        ['/pci/sonicvibes.c', 'SonicVibes driver'],
        ['/pci/via82xx.(c|patch)', 'VIA82xx driver'],
        ['/pci/sis7019.(c|h|patch)', 'SIS7019 driver'],
        ['/pci/bt87x.c', 'BT87x driver'],
        ['/pci/bt87x.patch', 'BT87x driver'],
        ['/pci/atiixp.(c|patch)', 'ATIIXP driver'],
        ['/pci/atiixp_modem.(c|patch)', 'ATIIXP-modem driver'],
        ['/pci/intel8x0m.c', 'Intel8x0-modem driver'],
        ['/pci/via82xx_modem.(c|patch)', 'VIA82xx-modem driver'],
        ['/pci/als300.c', 'Avance Logic ALS300/300+ driver'],
        ['/pci/Kconfig', 'PCI drivers'],
        ['/pci/Makefile', 'PCI drivers'],
        ['/pci/ca0106/.*', 'CA0106 driver'],
        ['/pci/hda/hda_codec.[ch]', 'HDA Codec driver'],
        ['/pci/hda/hda_patch.[ch]', 'HDA Codec driver'],
        ['/pci/hda/patch_.*', 'HDA Codec driver'],
        ['/pci/hda/hda_intel.c', 'HDA Intel driver'],
        ['/include/hda.*', 'HDA Codec driver'],
        ['/pci/hda/.*', 'HDA generic driver'],
        ['/pci/ad1889.*', 'AD1889 driver'],
        ['/pci/cs5535audio/.*', 'CS5535 driver'],
        ['/pci/cmi8788/.*', 'CMI8788 driver'],
        ['/pci/pcxhr/.*', 'Digigram PCXHR driver'],
        ['/include/hdspm.h', 'HDSPM driver'],
        ['/pci/riptide/.*', 'Conexant Riptide driver'],
        ['/pci/pci_iomap_compat.c', 'PCI iomap compatibility layer'],
        ['/pci/cs5530.c', 'CS5530 Cyrix/NatSemi VSA1 softaudio init'],
        ['/pci/oxygen/.*', 'CMI8788 (Oxygen) driver'],
        ['/pci/aw2/.*', 'Emagic Audiowerk 2'],
        ['/pci', 'ERROR'],
        ['/ppc/Makefile', 'PPC'],
        ['/ppc/Kconfig', 'PPC'],
        ['/ppc/awacs.(c|h|patch)', 'PPC AWACS driver'],
        ['/ppc/burgundy.(c|h)', 'PPC Burgundy driver'],
        ['/ppc/daca.c', 'PPC DACA driver'],
        ['/ppc/keywest.c', 'PPC Keywest driver'],
        ['/ppc/keywest_old.c', 'PPC Keywest driver'],
        ['/ppc/pmac.(c|h|inc|patch)', 'PPC PMAC driver'],
        ['/ppc/pmac_old.c', 'PPC PMAC driver'],
        ['/ppc/powermac.c', 'PPC PowerMac driver'],
        ['/ppc/tumbler.(c|h|patch)', 'PPC Tumbler driver'],
        ['/ppc/beep.(c|patch)', 'PPC Beep'],
        ['/ppc/beep_old.c', 'PPC Beep'],
        ['/ppc/toonie.c', 'PPC Toonie'],
        ['/ppc/snd_ps3.*', 'PPC PS3 driver'],
        ['/ppc', 'ERROR'],
        ['/i2c/l3', 'L3 drivers'],
        ['/include/tea575x-tuner.h', 'TEA575x tuner'],
        ['/i2c/other/tea575x-tuner.c', 'TEA575x tuner'],
        ['/include/ak4114.h', 'AK4114 receiver'],
        ['/i2c/other/ak4114.c', 'AK4114 receiver'],
        ['/include/ak4117.h', 'AK4117 receiver'],
        ['/i2c/other/ak4117.c', 'AK4117 receiver'],
        ['/include/ak4xxx-adda.h', 'AK4XXX AD/DA converters'],
        ['/i2c/other/ak4xxx-adda.c', 'AK4XXX AD/DA converters'],
        ['/i2c/other', 'Serial BUS drivers'],
        ['/include/i2c.h', 'I2C lib core'],
        ['/i2c/i2c.c', 'I2C lib core'],
        ['/include/cs8427.h', 'I2C cs8427'],
        ['/i2c/cs8427.c', 'I2C cs8427'],
        ['/i2c/tea6330t.c', 'I2C tea6330t'],
        ['/include/tea6330t.h', 'I2C tea6330t'],
        ['/include/uda1380.h', 'I2C UDA1380'],
        ['/i2c/uda1380.c', 'I2C UDA1380'],
        ['/i2c/Kconfig', 'I2C Kconfig'],
        ['/i2c', 'ERROR'],
        ['/spi/Kconfig', 'SPI Kconfig'],
        ['/spi/at73c213.(c|h)', 'Atmel AT73C213 DAC driver'],
        ['/spi', 'ERROR'],
        ['/parisc/harmony.[ch]', 'PARISC Harmony driver'],
        ['/parisc/Kconfig', 'PARISC'],
        ['/parisc', 'ERROR'],
        ['/sparc/amd7930.(c|patch)', 'SPARC AMD7930 driver'],
        ['/sparc/cs4231.(c|patch)', 'SPARC cs4231 driver'],
        ['/sparc/dbri.(c|patch)', 'SPARC DBRI driver'],
        ['/sparc/Kconfig', 'SPARC'],
        ['/sparc', 'ERROR'],
        ['/mips/au1x00.[ch]', 'MIPS AU1x00 driver'],
        ['/mips/hal2.[ch]', 'MIPS SGI A2 Audio System'],
        ['/mips/ad1843.[ch]', 'AD1843 driver'],
        ['/mips/sgio2audio.c', 'SGI O2 Audio'],
        ['/mips/Kconfig', 'MIPS'],
        ['/mips', 'ERROR'],
        ['/include/emux_synth.h', 'Common EMU synth'],
        ['/synth/emux', 'Common EMU synth'],
        ['/include/soundmem.h', 'Synth'],
        ['/synth/Makefile', 'Synth'],
        ['/synth/util_mem.c', 'Synth'],
        ['/include/util_mem.h', 'Synth'],
        ['/pcmcia/vx', 'Digigram VX Pocket driver'],
        ['/pcmcia/pdaudiocf', 'PDAudioCF driver'],
        ['/pcmcia/Kconfig', 'PCMCIA Kconfig'],
        ['/pcmcia/Makefile', 'PCMCIA'],
        ['/pcmcia', 'ERROR'],
        ['/include/soc.h', 'SoC Layer'],
        ['/include/soc-of-simple.h', 'SoC Layer'],
        ['/include/soc-dapm.h', 'SoC Dynamic Audio Power Management'],
        ['/include/l3.h', 'SoC L3 bus'],
        ['/include/uda134x.h', 'SoC Codec Philips UDA134x'],
        ['/include/s3c24xx_uda134x.h', 'SoC Audio for the Samsung S3C24XX chips'],
        ['/include/soc-dai.h', 'SoC Layer'],
        ['/soc/codecs/Kconfig', 'SoC Layer'],
        ['/soc/codecs/l3.(c|h)', 'SoC L3 bus'],
        ['/soc/codecs/ac97.(c|h)', 'SoC Codec AC97'],
        ['/soc/codecs/wm8350.(c|h)', 'SoC Codec WM8350'],
        ['/soc/codecs/wm8510.(c|h)', 'SoC Codec WM8510'],
        ['/soc/codecs/wm8560.(c|h)', 'SoC Codec WM8560'],
        ['/soc/codecs/wm8580.(c|h)', 'SoC Codec WM8580'],
        ['/soc/codecs/wm8728.(c|h)', 'SoC Codec WM8728'],
        ['/soc/codecs/wm8731.(c|h)', 'SoC Codec WM8731'],
        ['/soc/codecs/wm8750.(c|h)', 'SoC Codec WM8750'],
        ['/soc/codecs/wm8753.(c|h)', 'SoC Codec WM8753'],
        ['/soc/codecs/wm8900.(c|h)', 'SoC Codec WM8900'],
        ['/soc/codecs/wm8903.(c|h)', 'SoC Codec WM8903'],
        ['/soc/codecs/wm8971.(c|h)', 'SoC Codec WM8971'],
        ['/soc/codecs/wm8990.(c|h)', 'SoC Codec WM8990'],
        ['/soc/codecs/wm9705.(c|h)', 'SoC Codec WM9705'],
        ['/soc/codecs/wm9712.(c|h)', 'SoC Codec WM9712'],
        ['/soc/codecs/wm9713.(c|h)', 'SoC Codec WM9713'],
        ['/soc/codecs/cs4270.(c|h)', 'SoC Codec CS4270'],
        ['/soc/codecs/ad1980.(c|h)', 'SoC Codec AD1980'],
        ['/soc/codecs/tlv320aic23.(c|h)', 'SoC Codec TLV320AIC23'],
        ['/soc/codecs/tlv320aic26.(c|h)', 'SoC Codec TLV320AIC26'],
        ['/soc/codecs/tlv320aic3x.(c|h)', 'SoC Codec TLV320AIC3X'],
        ['/soc/codecs/uda134x.(c|h)', 'SoC Codec Philips UDA134x'],
        ['/soc/codecs/uda1380.(c|h)', 'SoC Codec Philips UDA1380'],
        ['/soc/codecs/ak4535.(c|h)', 'SoC Codec AK4535'],
        ['/soc/codecs/ssm2602.(c|h)', 'SoC Codec SSM2602'],
        ['/soc/codecs/ad73311.(c|h)', 'SoC Codec AD73311'],
        ['/soc/codecs/twl4030.(c|h)', 'SoC Codec TWL4030'],
        ['/soc/codecs/pcm3008.(c|h)', 'SoC Codec PCM3008'],
        ['/soc/codecs', 'ERROR'],
        ['/soc/atmel/.*', 'SoC Audio for the Atmel AT32/AT91 System-on-Chip'],
        ['/soc/at32/.*', 'SoC Audio for the Atmel AT32 System-on-Chip'],
        ['/soc/at91/.*', 'SoC Audio for the Atmel AT91 System-on-Chip'],
        ['/soc/pxa/spitz.c', 'SoC PXA2xx Spitz'],
        ['/soc/pxa/corgi.c', 'SoC PXA2xx Corgi'],
        ['/soc/pxa/poodle.c', 'SoC PXA2xx Poodle'],
        ['/soc/pxa/e800_wm9712.c', 'SoC PXA2xx E800/WM9712'],
        ['/soc/pxa/tosa.c', 'SoC PXA2xx Tosa'],
        ['/soc/pxa/pxa*', 'SoC PXA2xx Core'],
        ['/soc/pxa/em-x270*', 'SoC PXA2xx EM-X270'],
        ['/soc/pxa/palm27x*', 'SoC PXA2xx Palm T|X, T5 and LifeDrive'],
        ['/soc/pxa/zylonite*', 'SoC PXA2xx Zylonite'],
        ['/soc/pxa/e750_wm9705.c', 'SoC PXA2xx E750'],
        ['/soc/pxa/Kconfig', 'SoC PXA2xx Core'],
        ['/soc/s3c24xx/.*', 'SoC Audio for the Samsung S3C24XX chips'],
        ['/soc/sh/.*', 'SoC SH7760 AC97'],
        ['/soc/fsl/.*', 'SoC Freescale'],
        ['/soc/davinci/.*', 'SoC DaVinci'],
        ['/soc/omap/.*', 'SoC Texas Instruments OMAP'],
        ['/soc/au1x/.*', 'Au12x0/Au1550 PSC ASoC'],
        ['/soc/blackfin/.*', 'SoC Blackfin'],
        ['/soc/soc-core.*', 'SoC Layer'],
        ['/soc/soc-jack.*', 'SoC Layer'],
        ['/soc/Kconfig', 'SoC Layer'],
        ['/soc/soc-dapm.c', 'SoC Dynamic Audio Power Management'],
        ['/soc', 'ERROR'],
        ['/usb/usx2y/.*', 'USB USX2Y'],
        ['/usb/caiaq/.*', 'USB caiaq'],
        ['/usb/Kconfig', 'USB'],
        ['/usb/Makefile', 'USB'],
        ['/usb/usbaudio.(c|h|inc|patch)', 'USB generic driver'],
        ['/usb/usbmidi.(c|h|inc|patch)', 'USB generic driver'],
        ['/usb/usbmixer.(c|h|patch)', 'USB generic driver'],
        ['/usb/usbquirks.(c|h)', 'USB generic driver'],
        ['/usb/usbmixer_maps.c', 'USB generic driver'],
        ['/usb/usbcompat.h', 'USB generic driver'],
        ['/usb', 'ERROR'],
        ['/include/hal2.h', 'HAL2 driver'],
        ['/hal2/.*', 'HAL2 driver'],
        ['/aoa/.*', 'Apple Onboard Audio driver'],
        ['/sh/.*', 'Dreamcast AICA sound (pcm) driver'],
        ['/core/ioctl32', 'IOCTL32 emulation'],
        ['/include/pcm_oss.h', 'ALSA<-OSS emulation'],
        ['/include/mixer_oss.h', 'ALSA<-OSS emulation'],
        ['/core/oss', 'ALSA<-OSS emulation'],
        ['/core/seq/oss', 'ALSA<-OSS sequencer'],
        ['/include/ainstr..*', 'Instrument layer'],
        ['/core/seq/instr', 'Instrument layer'],
        ['/include/seq_.*.h', 'ALSA sequencer'],
        ['/include/asequencer.h', 'ALSA sequencer'],
        ['/core/seq', 'ALSA sequencer'],
        ['/core/Kconfig', 'ALSA Core'],
        ['/core/memalloc.*', 'Memalloc module'],
        ['/core/sgbuf.*', 'Memalloc module'],
        ['/core/rtctimer.*', 'RTC timer driver'],
        ['/core/hpetimer.*', 'HPE timer driver'],
        ['/core/hrtimer.*', 'HR timer driver'],
        ['/include/timer.h', 'Timer Midlevel'],
        ['/core/timer.*', 'Timer Midlevel'],
        ['/include/rawmidi.*', 'RawMidi Midlevel'],
        ['/core/rawmidi.*', 'RawMidi Midlevel'],
        ['/include/pcm.*', 'PCM Midlevel'],
        ['/core/pcm.*', 'PCM Midlevel'],
        ['/include/hwdep.*', 'HWDEP Midlevel'],
        ['/core/hwdep.*', 'HWDEP Midlevel'],
        ['/include/control.*', 'Control Midlevel'],
        ['/include/tlv.h', 'Control Midlevel'],
        ['/core/control.*', 'Control Midlevel'],
        ['/core/isadma.*', 'ISA DMA'],
        ['/core/vmaster.*', 'Virtual Master'],
        ['/include/jack.h', 'Jack Input Event Midlevel'],
        ['/core/jack.*', 'Jack Input Event Midlevel'],
        ['/include/adriver.h', 'ALSA Core'],
        ['/include/asound.h', 'ALSA Core'],
        ['/include/asoundef.h', 'ALSA Core'],
        ['/include/driver.h', 'ALSA Core'],
        ['/include/version.h', 'ALSA Version'],
        ['/include/initval.h', 'ALSA Core'],
        ['/include/minors.h', 'ALSA Minor Numbers'],
        ['/include/sndmagic.h', 'ALSA Core'],
        ['/include/info.h', 'ALSA Core'],
        ['/include/core.h', 'ALSA Core'],
        ['/include/memalloc.h', 'ALSA Core'],
        ['/include/config.h.in', 'ALSA Core'],
        ['/include/.*_compat.h', 'ALSA Core'],
        ['/include/compat_22.h', 'ALSA Core'],
        ['/include/linux/pci_ids.h', 'ALSA Core'],
        ['/include/autoconf.*', 'ALSA Core'],
        ['/include/platform_device_compat.h', 'ALSA Core'],
        ['/include/typedefs.h', 'ALSA Core'],
        ['/include/old/gf1.h', 'OLD GF1 header'],
        ['/include/old/.*.h', 'OLD headers'],
        ['/include/ppc-prom-hack.h', 'ALSA Core'],
        ['/include/Kbuild', 'ALSA Core'],
        ['/core/info.*', 'ALSA Core'],
        ['/core/control.*', 'ALSA Core'],
        ['/core/init.*', 'ALSA Core'],
        ['/core/sound.*', 'ALSA Core'],
        ['/core/device.*', 'ALSA Core'],
        ['/core/memory.*', 'ALSA Core'],
        ['/core/misc.*', 'ALSA Core'],
        ['/core/wrappers.*', 'ALSA Core'],
        ['/core/pci_compat_22.c', 'ALSA Core'],
        ['/core/Makefile', 'ALSA Core'],
        ['/core', 'ERROR'],
        ['/Documentation/.*', 'Documentation'],
        ['/doc/.*', 'Documentation'],
        ['/include', 'ERROR'],
        ['/kernel/MAINTAINERS', 'MAINTAINERS file'],
        ['/kernel/CREDITS', 'CREDITS file'],
        ['/kernel/include/linux/pci_ids.h', 'pci_ids.h update'],
        ['/kernel/include/linux/i2c-id.h', 'ic2-id.h update'],
        ['/kernel/drivers/media/video/saa7134/.*', 'SAA7134 driver'],
        ['/kernel/drivers/media/video/cx88/.*', 'CX88 driver'],
        ['/kernel/drivers/input/touchscreen/ucb1400_ts.*', 'USB1400 touchscreen driver'],
        ['/kernel/drivers/usb/gadget/gmidi.*', 'USB MIDI Gadget driver'],
        ['/kernel/arch/arm/mach-pxa/mainstone.c', 'PXA Mainstone driver'],
        ['/kernel/include/asm-arm/arch-pxa/audio.h', 'PXA Mainstone driver'],
        ['/kernel/include/asm-arm/arch-omap/.*', ':"ARM/OMAP driver'],
        ['/kernel/include/linux/spi/at73c213.h', 'Atmel AT73C213 DAC driver'],
        ['/kernel', 'ERROR'],
        ['/misc/ac97_bus.c', 'AC97 bus driver'],
        ['/sound_core.c', 'OSS device core'],
        ['/sound_firmware.c', 'OSS firmware core'],
        ['/ac97_bus.c', 'AC97 bus driver'],
        ['/scripts', 'IGNORE'],
        ['/utils', 'Utils'],
        ['/support', 'Support code for old kernels'],
        ['/last.c', 'Sound Core'],
        ['/Kconfig', 'Sound Core'],
        ['/Makefile', 'Sound Core'],
        ['/INSTALL', 'Sound Core'],
        ['/SUPPORTED_KERNELS', 'Sound Core'],
        ['/MAINTAINERS', 'MAINTAINERS file'],
        ['/Rules.make', 'Sound Core'],
        ['/configure.in', 'Sound Core'],
        ['/kconfig.vers', 'Sound Core'],
        ['/cvscompile', 'cvscompile script'],
        ['/hgcompile', 'hgcompile script'],
        ['/gitcompile', 'gitcompile script'],
        ['/snddevices.in', 'snddevices script'],
        ['/make-alsa-kernel', 'IGNORE'],
        ['/', 'ERROR'],
    ],
    "alsa-tools": [
        ['/envy24control/.*', 'Envy24 Control'],
        ['/rmedigicontrol/.*', 'RME Digi Control'],
        ['/pcxhrloader/.*', 'Digigram PCXHR Loader'],
        ['/hdsploader/.*', 'RME HDSP Loader'],
        ['/echomixer/.*', 'Digigram Echo Mixer'],
        ['/as10k1/.*', 'as10k1 (EMU10K1+ DSP Assembler)'],
        ['/ld10k1/.*', 'ld10k1 (EMU10K1+ DSP Code Loader)'],
        ['/ac3dec/.*', 'ac3dec (Dolby Digital Decoder)'],
        ['/qlo10k1/.*', 'qlo10k1'],
        ['/hdspconf/.*', 'hdspconf'],
        ['/hdspmixer/.*', 'hdspmixer'],
        ['/vxloader/.*', 'vxloader'],
        ['/us428control/.*', 'us428control'],
        ['/mixartloader/.*', 'mixartloader'],
        ['/sb16_csp/.*', 'sb16_csp'],
        ['/sscape_ctl/.*', 'sscape_ctl'],
        ['/usx2yloader/.*', 'usx2yloader'],
        ['/seq/sbiload/.*', 'sbiload'],
        ['/seq/cvscompile', 'Core'],
        ['/seq/hgcompile', 'Core'],
        ['/seq/gitcompile', 'Core'],
        ['/seq/.*', 'ERROR'],
        ['/Makefile', 'Core'],
        ['/cvscompile', 'Core'],
        ['/hgcompile', 'Core'],
        ['/gitcompile', 'Core'],
        ['/compile', 'Core'],
        ['/', 'ERROR'],
    ],
    "alsa-lib": [
        ['/include/sound/.*', 'Kernel Headers'],
        ['/include/asound.*', 'Core'],
        ['/include/local.*', 'Core'],
        ['/include/global*', 'Core'],
        ['/include/conv.h', 'Core'],
        ['/include/error.h', 'Core'],
        ['/include/conf.h', 'Config API'],
        ['/include/control.h', 'Control API'],
        ['/include/control_external.h', 'External Control Plugin SDK'],
        ['/include/hwdep.h', 'HWDEP API'],
        ['/include/(input|output).h', 'I/O API'],
        ['/include/instr.h', 'Instrument API'],
        ['/include/mixer.h', 'Mixer API'],
        ['/include/mixer_abst.h', 'Mixer Abstraction API'],
        ['/include/mixer_ordinary.h', 'Mixer Ordinary API'],
        ['/include/rawmidi.h', 'Rawmidi API'],
        ['/include/timer.h', 'Timer API'],
        ['/include/seq.*', 'Sequencer API'],
        ['/include/pcm.h', 'PCM API'],
        ['/include/pcm_old.h', 'PCM API'],
        ['/include/pcm_ordinary.h', 'PCM Ordinary API'],
        ['/include/pcm_plugin.h', 'PCM Plugin API'],
        ['/include/pcm_external.h', 'External PCM Plugin SDK'],
        ['/include/pcm_ioplug.h', 'External PCM I/O Plugin SDK'],
        ['/include/pcm_extplug.h', 'External PCM Filter Plugin SDK'],
        ['/include/pcm_rate.h', 'External Rate Converter Plugin SDK'],
        ['/include/alsa-symbols.h', 'Core'],
        ['/include/iatomic.h', 'Core'],
        ['/src/control/.*', 'Control API'],
        ['/src/mixer/.*', 'Mixer API'],
        ['/include/pcm.h', 'PCM API'],
        ['/src/alisp/.*', 'ALSA Lisp'],
        ['/src/pcm/.*', 'PCM API'],
        ['/src/rawmidi/.*', 'RawMidi API'],
        ['/src/timer/.*', 'Timer API'],
        ['/src/seq/.*', 'Sequencer API'],
        ['/src/instr/.*', 'Instrument API'],
        ['/src/hwdep/.*', 'HWDEP API'],
        ['/src/ordinary_mixer/.*', 'Mixer Ordinary API'],
        ['/src/ordinary_pcm/.*', 'PCM Ordinary API'],
        ['/src/input.*', 'I/O subsystem'],
        ['/src/output.*', 'I/O subsystem'],
        ['/src/conf.*', 'Configuration'],
        ['/src/async.*', 'Async helpers'],
        ['/src/error.*', 'Error handler'],
        ['/src/socket.*', 'Socket helpers'],
        ['/src/userfile.*', 'Filename helpers'],
        ['/src/dlmisc.*', 'Dynamic Loader helpers'],
        ['/src/names.*', 'Device Name API'],
        ['/src/shmarea.*', 'SHM helpers'],
        ['/src/Versions', 'Core'],
        ['/modules/mixer/simple/.*', 'Simple Abstraction Mixer Modules'],
        ['/aserver/.*', 'ALSA Server'],
        ['/doc/.*', 'Documentation'],
        ['/utils/.*', 'Utils'],
        ['/test/.*', 'Test/Example code'],
        ['/m4/.*', 'Core'],
        ['/configure.in', 'Core'],
        ['/INSTALL', 'Documentation'],
        ['/NOTES', 'Documentation'],
        ['/cvscompile', 'Core'],
        ['/hgcompile', 'Core'],
        ['/gitcompile', 'Core'],
        ['/', 'ERROR'],
    ],
    "alsa-firmware": [
        ['/vxloader/.*', 'Digigram Vx Firmware'],
        ['/mixartloader/.*', 'Digigram MixArt Firmware'],
        ['/pcxhrloader/.*', 'Digigram PCXHR Firmware'],
        ['/echoaudio/.*', 'Digigram Echo Audio Firmware'],
        ['/hdsploader/.*', 'RME HDSP Firmware'],
        ['/usx2yloader/.*', 'Tescam USX2Y Firmware'],
        ['/asihpi/.*', 'AudioScience ASIHPI Firmware'],
        ['/emu/.*', 'EMU Firmware'],
        ['/emi_26_62/.*', 'Emagic EMI 2|6 Audio Interface Firmware'],
        ['/wavefront/.*', 'Wavefront Firmware'],
        ['/ymfpci/.*', 'Yamaha PCI (YMFPCI) Firmware'],
        ['/korg1212/.*', 'Korg 1212 Firmware'],
        ['/maestro3/.*', 'Maestro3 Firmware'],
        ['/sb16/.*', 'SB16 (CSP) Firmware'],
        ['/aica/.*', 'AICA (Dreamcast) Firmware'],
        ['/configure.in', 'Core'],
        ['/Makefile.am', 'Core'],
        ['/README', 'Core'],
        ['/cvscompile', 'Core'],
        ['/hgcompile', 'Core'],
        ['/gitcompile', 'Core'],
        ['/', 'ERROR'],
    ],
    "alsa-plugins": [
        ['/ctl/oss/.*', 'OSS Mixer -> ALSA Control plugin'],
        ['/oss/.*', 'OSS Mixer -> ALSA Control plugin'],
        ['/jack/.*', 'Jack PCM plugin'],
        ['/pcm/jack/.*', 'Jack PCM plugin'],
        ['/oss/.*', 'OSS PCM -> ALSA PCM plugin'],
        ['/pcm/oss/.*', 'OSS PCM -> ALSA PCM plugin'],
        ['/polyp/.*', 'Polyp -> ALSA plugin'],
        ['/pulse/.*', 'PulseAudio -> ALSA plugin'],
        ['/rate/.*', 'Rate Converter plugins'],
        ['/doc/.*', 'Documentation'],
        ['/a52/.*', 'A52 Output plugin'],
        ['/mix/.*', 'Automatic upmix / downmix plugins'],
        ['/maemo/.*', 'Alsa support for Maemo SDK (n770)'],
        ['/pph/.*', 'Public Parrot Hack rate converter'],
        ['/rate-lavc/.*', "libavcodec's resampler"],
        ['/usb_stream/.*', 'USB stream plugin'],
        ['/m4/.*', 'Core'],
        ['/COPYING.GPL', 'Core'],
        ['/COPYING', 'Core'],
        ['/configure.in', 'Core'],
        ['/cvscompile', 'Core'],
        ['/hgcompile', 'Core'],
        ['/gitcompile', 'Core'],
        ['/', 'ERROR'],
    ],
    "alsa-python": [
        ['/pyalsa/alsacard.c', 'pyalsa.alsacard module'],
        ['/pyalsa/alsacontrol.c', 'pyalsa.alsacontrol module'],
        ['/pyalsa/alsahcontrol.c', 'pyalsa.alsahcontrol module'],
        ['/pyalsa/alsamixer.c', 'pyalsa.alsamixer module'],
        ['/pyalsa/alsaseq.c', 'pyalsa.alsaseq module'],
        ['/pyalsa/mixertest[12].py', 'IGNORE'],
        ['/pyalsa/cardtest[12].py', 'IGNORE'],
        ['/pyalsa/hctltest[12].py', 'IGNORE'],
        ['/setup.py', 'Core'],
        ['/PKG-INFO', 'Core'],
        ['/MANIFEST.in', 'Core'],
        ['/utils/.*', 'Python utilities'],
        ['/test/.*', 'Test python scripts'],
        ['/tools/.*', 'Tools python scripts'],
        ['/doc/.*', 'Documentation'],
        ['/', 'ERROR'],
    ],
    "alsa-oss": [
        ['/alsa/pcm.c', 'PCM Emulation'],
        ['/alsa/mixer.c', 'Mixer Emulation'],
        ['/alsa/stdioemu.c', 'Core'],
        ['/alsa/alsa-oss.c', 'Core'],
        ['/alsa/Makefile.am', 'Core'],
        ['/alsa/aoss.1', 'Manual Page'],
        ['/alsa/aoss.in', 'aoss script'],
        ['/alsa/aoss.old.in', 'aoss script'],
        ['/include/version.h', 'ALSA Version'],
        ['/configure.in', 'Core'],
        ['/cvscompile', 'Core'],
        ['/hgcompile', 'Core'],
        ['/gitcompile', 'Core'],
        ['/', 'ERROR'],
    ],
}